# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ea1775d03ccb08ad297412148f0d5fa050d860d8dde97c38657b7745f8a64bc4269e933b80468df77c5e5313407d0bc0d9c5d5911596f264dabf938c491c583

test:
  secret_key_base: 7481233eb14a1b53d80cfb6afc89abc42e31d6cd0a180346c02eae8bd1aaea8c03746e4c0b7ac82ddac57c087deecabab23625e28735e905caf4c7a0b5b8344e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
